- name: Install apache server
  apt:
    name: apache2
    state: present

- name: Start and enable apache server
  service:
    name: apache2
    state: started
    enabled: yes

- name: Copy the index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: restart apache

